### ISSUE TITLE
Drop IE9 support?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfpb-chart-builder#107]
IE9 traffic is <0.1% on consumerfinance.gov. Shall we strip out IE9 support?

**Comment by marteki** [comment]
@anselmbradford I think that'd be okay, but what's the latest guidance on IE9 from our FEWD development standards?

Also, can we look at analytics specifically for the two cf.gov products that use this package (Consumer Credit Trends and Mortgage Performance Trends) to get more focused stats on browser usage?

**Comment by anselmbradford** [comment]
> I think that'd be okay, but what's the latest guidance on IE9 from our FEWD development standards?

Currently the charts are not displayed, because IE9 has the `no-js` class added to the page, which collapses the charts https://github.com/cfpb/cfpb-chart-builder/blob/master/src/css/cfpb-chart-builder.less#L853 

E.g.

![screen shot 2018-08-03 at 10 20 20 am](https://user-images.githubusercontent.com/704760/43647858-de05e19e-9706-11e8-9d63-bd0dad438a5a.png)


> Also, can we look at analytics specifically for the two cf.gov products that use this package (Consumer Credit Trends and Mortgage Performance Trends) to get more focused stats on browser usage?

All `/data-research/consumer-credit-trends/auto-loans/` pages  had 0 IE9 visitors in past 30 days, except for `/data-research/consumer-credit-trends/auto-loans/lending-borrower-age/`, which had 3 IE9 visitors or 0.00000416% of total site traffic.

All `/data-research/consumer-credit-trends/mortgages/` pages had 0 IE9 visitors in the past 30 days.

I checked these by going to Behavior > Site Content > All Pages, selecting Month as the timespan, selecting a Secondary Dimension of browser version (unfortunately it does not allow both browser name and version together, but it appears IE9 is the only thing that shows with a version value of "9").

Considering the low visitor numbers and that IE9 is already hiding the charts, I will look to remove IE9 related polyfilling and cruft unless there are any objections.

**Comment by marteki** [comment]
```
// Collapse chart containers when JS is disabled 
.no-js {
```

Ah! I don't think I realized the implications of that development decision before. But based on lack of usage, it might not matter that much or at all.

And I just checked the same analytics for all the Mortgage Performance Trends pages for July 2018. Only one pageview using IE9, which only looked at `/data-research/mortgage-performance-trends/` (not any of the pages with charts).

:+1: from me for removing the IE9 polyfilling, etc.

**Comment by cfarm** [comment]
> All /data-research/consumer-credit-trends/mortgages/ pages had 0 IE9 visitors in the past 30 days.

IE9 has been turned off for these pages for months due to the cfgov-refresh update, so we should check date from before this change: https://github.com/cfpb/cfgov-refresh/pull/3693

I am against downgrading our browser support further since

A) There are probably other higher-priority changes
B) I don't see an argument for the upside of this -what performance or maintenance improvement do we gain?
C) We might be able to maintain support for IE9 easily, since the Highcharts library that chart-builder uses supports it, and keeping our content accessible to more browsers is a win when it's not detracting from the experience of other users. This also follows our stated browser support standards:

> We always prefer to build features that work for any browser. When that's either impossible or impractical, we start with a basic experience, and build additional features on top.

I'm voting for creating an issue for investigating option C, timeboxing it and making it a lower priority, and otherwise putting a hold on ie9 related changes in favor of higher priority work for the time being.

**Comment by marteki** [comment]
I rescind my earlier thumbs up, and support @cfarm's standpoint as it's full of great points. Thank you for providing the browser support standards info, and clarifying that the current experience for IE9 is NOT intended.

**Comment by anselmbradford** [comment]
> IE9 has been turned off for these pages for months due to the cfgov-refresh update, so we should check date from before this change: cfpb/cfgov-refresh#3693

Okay, with Kelley's help tested this another way, which may be helpful for checking the analytics overall. I went to Audience > Browser & OS > Add Segment > click new segment > go to advanced, conditions > change the dropdown to "Page" > change the contains dropdown to "matches regex" to `/data-research/consumer-credit-trends/` > click "Save." Click into IE9. Add "Page" as the secondary dimension > Then filter on "/data-research/consumer-credit-trends/". This shows each browser to the `/data-research/consumer-credit-trends/` section.

For the date range Jul 27, 2017-Aug 2, 2018:

- `/data-research/consumer-credit-trends/auto-loans/origination-activity/` 5 users.
- `/data-research/consumer-credit-trends/auto-loans/borrower-risk-profiles/` 2 users.
- `/data-research/consumer-credit-trends/auto-loans/lending-neighborhood-income-level/` 2 users.
- `/data-research/consumer-credit-trends/auto-loans/lending-borrower-age/` 2 users.
 - `/data-research/consumer-credit-trends/credit-cards/origination-activity/` 2 users.
 - `/data-research/consumer-credit-trends/credit-cards/borrower-risk-profiles/` 2 users.
 - `/data-research/consumer-credit-trends/credit-cards/lending-neighborhood-income-level/` 1 user.
- `/data-research/consumer-credit-trends/credit-cards/lending-borrower-age/` 1 user.
- `/data-research/consumer-credit-trends/mortgages/origination-activity/` 1 user.
- `/data-research/consumer-credit-trends/mortgages/borrower-risk-profiles/` 0 users.
- `/data-research/consumer-credit-trends/mortgages/lending-neighborhood-income-level/` 0 users.
- `/data-research/consumer-credit-trends/mortgages/lending-borrower-age/` 0 users.
- `/data-research/consumer-credit-trends/student-loans/origination-activity/` 0 users.
- `/data-research/consumer-credit-trends/student-loans/borrower-risk-profiles/` 0 users.
- `/data-research/consumer-credit-trends/student-loans/lending-neighborhood-income-level/` 0 users.
- `/data-research/consumer-credit-trends/student-loans/lending-borrower-age/` 0 users.

For all pages within `/data-research/consumer-credit-trends/` there were 40 users using IE9. This includes chart and non-chart pages within CCT.

For mortgage performance:

- `/data-research/mortgage-performance-trends/mortgages-30-89-days-delinquent/` 0 users.
- `/data-research/mortgage-performance-trends/mortgages-90-or-more-days-delinquent/` 0 users.

The highest visitor count, 5 users to `/data-research/consumer-credit-trends/auto-loans/origination-activity/`, represents 0.00004% of total visitors to the site during that time period.

> A) There are probably other higher-priority changes

Happy to take on any higher priority things if the team wants to assign me to any.

> B) I don't see an argument for the upside of this -what performance or maintenance improvement do we gain?

It appears we could:
- Remove some of the polyfills included in the generated script https://github.com/cfpb/cfpb-chart-builder/blob/67d13b587e1dd56414d37c81151d416ac881a842/src/js/index.js#L3-L4 (symbol and promise are presumably needed for IE10/11, but we might want to look at those too and see if core-js module could be completely removed).
- Eliminate the check for http https://github.com/cfpb/cfpb-chart-builder/blob/1115bab7c715a8d0c338a0eea5f448b1d8602432/src/js/utils/map-shapes.js#L6 (this could happen anyway I think).
- Eliminate the several references to https://github.com/cfpb/cfpb-chart-builder/blob/11bfca148a6ddb40bb3bd1128814f85b647783bf/src/css/cfpb-chart-builder.less#L15 and provide one hide condition for the whole graph for `.lt-ie10`.

> C) We might be able to maintain support for IE9 easily

Highcharts appears to be moving toward dropping support, as [6.x includes `Decoupled old IE code into a separate module.`](https://github.com/highcharts/highcharts/blob/master/changelog/highcharts/6.0.0.md#changelog-for-highcharts-v600-2017-10-04), if it's possible to exclude the old IE code from the highcharts that's included, that would further reduce the chart builder generated script size.
