### ISSUE TITLE
Private methods appear not to be used.

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfpb-chart-builder#111]
## Current behavior

[_getYAxisUnits](https://github.com/cfpb/cfpb-chart-builder/blob/master/src/js/charts/LineChart.js#L36), [_getYAxisUnits](https://github.com/cfpb/cfpb-chart-builder/blob/master/src/js/charts/LineChartComparison.js#L36), [_getYAxisLabel](https://github.com/cfpb/cfpb-chart-builder/blob/master/src/js/charts/LineChartComparison.js#L50) appear not to be used.

## Expected behavior

Unused methods that are not part of the public API of a module should be removed.

**Comment by marteki** [comment]
@anselmbradford if the new charts to be added will use different units than the current ones, does that affect how we should deal with this?

**Comment by anselmbradford** [comment]
No it shouldn't. These methods appear to be unused and could be completely deleted without any change in functionality. @contolini @mistergone do you see a use here I'm not seeing (looks like you touched these).

**Comment by anselmbradford** [comment]
These have been removed.
