### ISSUE TITLE
Broken JSON in demo page

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfpb-chart-builder#113]
## Current behavior

https://cfpb.github.io/cfpb-chart-builder/ shows error `Uncaught SyntaxError: Unexpected token < in JSON at position 0`

## Expected behavior

Demo page referenced in Readme should work.

**Comment by cfarm** [comment]
@hillaryj This appears to be the same CORS issue that was affecting cf.gov. Can we get the URL https://cfpb.github.io able to serve the JSON files?

**Comment by hillaryj** [comment]
I'm seeing that `Unexpected token` error after a 404 when trying to load the data file.

I'm looking at the console info:
- the page gets a 404 when trying to access https://cfpb.github.io/sample_data/mortgage-performance/time-series/30-89/national
- if I go to https://cfpb.github.io/sample_data/mortgage-performance/time-series/30-89/national directly, I also get a 404
- that data file is actually at https://github.com/cfpb/cfpb-chart-builder/blob/master/test/sample_data/mortgage-performance/time-series/30-89/national

This may be a mismatch of data sources and not a CORS issue. For the CORS issue, we could load the resource directly but the page was blocked with a cross-site-specific message in the console.

**Comment by anselmbradford** [comment]
When the demo page is fixed, it should be added as a syncing step in the GitHub Actions. See https://github.com/cfpb/cfpb-chart-builder/pull/182#discussion_r480276755
