### ISSUE TITLE
Audit Section 508 compliance

### ISSUE THREAD

**Issue by contolini** [cfpb/cfpb-chart-builder#17]
We know Highcharts offers keyboard navigation and is kind to screen readers but we need to formally verify its accessibility.

See https://github.com/cfpb/development/blob/master/accessibility.md and http://www.highcharts.com/docs/chart-concepts/accessibility

> Enabling the Accessibility module goes a long way to ensure that your charts comply with existing accessibility standards, including the Section 508 standard of the US Government, and the international WCAG 2.0 standard.

**Comment by cfarm** [comment]
We've added keyboard navigation settings and we have scheduled a screenreader test using JAWS as a next step.
