### ISSUE TITLE
use Yarn

### ISSUE THREAD

**Issue by cfarm** [cfpb/cfpb-chart-builder#170]
## Current behavior
This repo uses npm. In order to test out changes in this codebase in cfgov-refresh, one has to manually copy the project repo into cfgov-refresh's `node_modules` folder, then delete and re-install cfpb-chart-builder when done. Copying the folder manually can take 5 minutes or so of time each time. When actively working on multiple branches within cfgov-refresh, re-doing this multiple times a day adds up.

## Expected behavior
Use Yarn in this repo so we can `yarn link` this package with cfgov-refresh and test our code changes more easily with the Consumer Credit Trends and Mortgage Performance Trends pages. We can then `yarn unlink` to remove the link and to re-add the published cfpb-chart-builder once we have finished with testing.

**Comment by Scotchester** [comment]
While I agree that we should switch to Yarn here, I think that using either `npm link` or `yarn link` would still work, since they're basically just easier ways to create fancy symlinks.

**Comment by cfarm** [comment]
I haven't tried it out of fear of breaking stuff while mid-development, have you?

**Comment by cfarm** [comment]
i made a minimal attempt at running`npm link` here and then `yarn link cfpb-chart-builder` in cfgov-refresh but it failed and gave me this error:

`error No registered package found called "cfpb-chart-builder".`

**Comment by cfarm** [comment]
Ooh ok thanks. So this task can become just documenting that in the readme, for testing in cfgov-refresh. Thanks!

**Comment by wpears** [comment]
This was fixed in the referenced PR
