### ISSUE TITLE
Debug IE 8

### ISSUE THREAD

**Issue by contolini** [cfpb/cfpb-chart-builder#18]
Sauce Labs is reporting the charts ain't loading in IE 8. See https://travis-ci.org/cfpb/cfpb-chart-builder/builds/195359327#L526

Crack it open in VirtualBox and see what's up.

**Comment by contolini** [comment]
Turns out the culprit is the CSV-parsing library we use: https://github.com/mholt/PapaParse/issues/23

**Comment by cfarm** [comment]
Highcharts has a data processing module. I'm checking for browser support rn:

http://www.highcharts.com/docs/working-with-data/data-module

**Comment by cfarm** [comment]
Highcharts overall compatibility is back to IE6 according to its docs.  tested the live demo of the data module csv parse thingy in ie8 and it works. http://www.highcharts.com/docs/working-with-data/data-module

**Comment by contolini** [comment]
Eh gad we should have been using that all along.

**Comment by contolini** [comment]
Re: IE8, we'll also need some polyfills for things like `forEach` and `Object.keys()` (or we can just not use those methods). And I bet we have some [dangling commas](https://satishchilukuri.com/blog/entry/ie-8-and-trailing-commas-in-javascript), linting PR incoming.

**Comment by cfarm** [comment]
let's just not use the things that don't work if we can avoid it? ALSO: do we need this before tuesday? I'm adding to GHE board just in case.

**Comment by contolini** [comment]
Some notes on what would need to be done for IE8 support:

Replace:
- CSV parsing library

Add polyfills for:
- `forEach`
- `map`
- `Object.keys()`

Remove:
- Dangling commas (linting has taken care of this)
