### ISSUE TITLE
Upgrade Highcharts when new version is released

### ISSUE THREAD

**Issue by cfarm** [cfpb/cfpb-chart-builder#42]
The next version of Highcharts to get released should contain the bug fix we reported for ie8: https://github.com/highcharts/highcharts/issues/6361

I signed up for their release notifications, since we'll have to:

- [ ] undo [the interim fix PR](https://github.com/cfpb/cfpb-chart-builder/pull/39)
- [x]  upgrade the package.json version of Highcharts in chart-builder
- [ ] publish new chart builder version
- [ ]  release on cfgov-refresh

**Comment by marteki** [comment]
Hey, did this get done?

**Comment by cfarm** [comment]
Hooray, the latest version of Highcharts (v5.0.9) has @mistergone's fix! https://github.com/highcharts/highcharts/commit/bbb4b9962bb6a4c895b19e12e908c9a16be5f164

I'm working on this task today, which will also help us solve the #49 CSS styling pr

**Comment by cfarm** [comment]
Here's the actual fix in the release tagged 5.0.9 https://github.com/highcharts/highcharts/blob/v5.0.9/js/modules/accessibility.src.js#L167

**Comment by cfarm** [comment]
PR https://github.com/cfpb/cfpb-chart-builder/pull/50
