### ISSUE TITLE
Tag and release CSS-powered charts

### ISSUE THREAD

**Issue by contolini** [cfpb/cfpb-chart-builder#55]
@cfarm how are you feeling about your CSS improvements? Is it safe to create a tag and push the changes to cfgov-refresh?

I'm thinking we should bump the library to 2.0.0 because there's now a CSS requirement.

**Comment by cfarm** [comment]
There was always a CSS requirement but I do think it's a big enough change to justify that.

**Comment by cfarm** [comment]
Also yes I am working on this this sprint!

**Comment by contolini** [comment]
👍

**Comment by cfarm** [comment]
Done: https://github.com/cfpb/cfpb-chart-builder/releases/tag/v2.0.0

Upgrading in cfgov-refresh next:
https://github.com/cfpb/cfgov-refresh/pull/3173
