### ISSUE TITLE
Convert older chart types to classes

### ISSUE THREAD

**Issue by cfarm** [cfpb/cfpb-chart-builder#71]
In this PR https://github.com/cfpb/cfpb-chart-builder/pull/68/files#diff-99a85c3932c0670278158f38d818e0efR32 for Mortgage Performance charts, the new LineComparison chart is created as a class. 

It would be nice to make the other chart types (bar, line, tile_map) classes too, so that creating and updating charts is consistent for all the chart types.

Best timing for this would be after Mortgage Performance launch, to avoid introducing new bugs to the existing charts in Consumer Credit Trends.

**Comment by anselmbradford** [comment]
Line chart is converted to a class in https://github.com/cfpb/cfpb-chart-builder/pull/135

**Comment by anselmbradford** [comment]
Remaining charts converted to classes in https://github.com/cfpb/cfpb-chart-builder/pull/152/

**Comment by anselmbradford** [comment]
Fixed in https://github.com/cfpb/cfpb-chart-builder/pull/152
