### ISSUE TITLE
Change highcharts import from 'inline' to 'less'

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfpb-chart-builder#84]
Is `(inline)` needed for some reason on https://github.com/cfpb/cfpb-chart-builder/blob/master/src/css/cfpb-chart-builder.less#L1? Change to `(less)`, see background in https://github.com/cfpb/cfgov-refresh/issues/3498#issuecomment-338092625.

**Comment by sebworks** [comment]
@contolini, @cfarm, does this need to be `inline`

**Comment by cfarm** [comment]
if the `(less)` works just as well within cfgov-refresh then nope.
