### ISSUE TITLE
Sauce tests not working

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfpb-chart-builder#91]
I run `npm run test` and the output gets stuck in endless feedback that the tests are still running:
```
> cfpb-chart-builder@3.2.1 browser-tests /Users/bradforda/Projects/cfpb-chart-builder
> CI_ENVIRONMENT=true node test/browser-tests.js

Local server listening to 8089
Sauce Connect ready.
Tests started.
Tests still running... See status at https://saucelabs.com/u/bradforda
Tests still running... See status at https://saucelabs.com/u/bradforda
…
```

I checked in Sauce and I don't see any tests running (I do see 1 active tunnel).

## Current behavior
- Terminal output reports Sauce tests running, but no tests appear to be running in Sauce.
- [User URL for tests](https://github.com/cfpb/cfpb-chart-builder/blob/master/test/browser-tests.js#L117) is incorrect and 404s. Current URL in Sauce is https://saucelabs.com/beta/dashboard/manual

## Expected behavior
- Sauce tests should be running on Sauce.
- Terminal output status URL is a live URL.

## Steps to replicate behavior (include URLs)

1. Run `./setup.sh && npm run test`

**Comment by marteki** [comment]
I can see the tests you ran on Dec 29th on the "Automated Tests" tab in Sauce right now. They are appearing on the user URL, which is https://saucelabs.com/u/cct-sauce. It's the same link provided in the Sauce badge in the heading of the readme.

Was something else happening around this bug? Or was it broken, and you were able to fix it?

**Comment by anselmbradford** [comment]
Hmmm… so I have my own Sauce credentials in `test/config.json` and went to the URL per the Terminal output instructions, which 404s. Going to the "Automated Tests" tab in my account I don't see the tests. I don't understand how it would be using the cct-sauce account if I have my own credentials in `test/config.json`.

**Comment by marteki** [comment]
Did you check out the testing instructions in the README? https://github.com/cfpb/cfpb-chart-builder#testing

It has instructions for a `test/config.json` setup. Maybe see where your local is deviating from that?

**Comment by anselmbradford** [comment]
Yeah, followed those. Does anyone else have a Sauce account other than cct-sauce that can test?

**Comment by contolini** [comment]
Update: The [tests](https://github.com/cfpb/cfpb-chart-builder/blob/master/test/browser-tests.js#L66) are tied to the `cct-sauce` Sauce Labs account so you'll have to use those credentials. We could make them account-agnostic but the user would have to be on a plan that allows at least 5 parallel VMs. IMHO it's easier to just tell colleagues to copy/paste the provided credentials.

**Comment by anselmbradford** [comment]
Prolly should set `cct-sauce` in https://github.com/cfpb/cfpb-chart-builder/blob/master/test/config.json.example#L2
